version: '3.8'

services:
  dev-db:
    image: postgres:14.9-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: dev-password
      POSTGRES_DB: test
      POSTGRES_ADMIN_PASSWORD: dev-admin-password